import requests
parameters = {
        "amount":10,
        "type":"boolean",
}
response = requests.get("https://opentdb.com/api.php",params=parameters)
response.raise_for_status()
data = response.json()
question_data = data['results']

# question_data = [
#         {"text":"Sharks are mammals.","answer":"False",},
#         {"text":"Sea otters have a favorite rock they use to break open food","answer":"True",},
#         {"text":"The blue whale is the biggest animal to have ever lived.","answer":"True",},
#         {"text":"The hummingbird egg is the world's smallest bird egg.","answer":"True",},
#         {"text":"Pigs roll in the mud because they don't like being clean.","answer":"False",},
#         {"text":"Bats are blind.","answer":"False",},
#         {"text":"A dog sweats by panting its tongue.","answer":"False",},
#         {"text":"It takes a sloth two weeks to digest a meal.","answer":"True",},
#         {"text":"The largest living frog is the Goliath frog of West Africa.","answer":"True",},
#         {"text":"An ant can lift 1,000 times its body weight.","answer":"False",},
#         {"text":"When exiting a cave, bats always go in the direction of the wind.","answer":"False",},
#         {"text":"Galapagos tortoises sleep up to 16 hours a day.","answer":"True",},
#         {"text":"An octopus has seven hearts.","answer":"False",},
#         {"text":"The goat is the national animal of Scotland.","answer":"False",},
#         {"text":"Herbivores are animal eaters.","answer":"False",},
#         {"text":"A monkey was the first non-human to go into space.","answer":"False",},
#         {"text":"New York City is composed of between 36 and 42 islands.","answer":"True",},        
#         {"text":"South Africa has one capital.","answer":"False",},
#         {"text":"The Atlantic Ocean is the biggest ocean on Earth.","answer":"False",},
#         {"text":"Mount Everest is the tallest mountain in the world.","answer":"True",},
#         {"text":"You can find the 'Desert of Death' in California.","answer":"False",},
#         {"text":"The total length of the Great Wall of China adds up to 13,171 miles.","answer":"True",},
#         {"text":"The two longest rivers in the world are the Mississippi and the Nile.","answer":"False",},
#         {"text":"The Chunnel between England and France is 31.5 miles long.","answer":"True",},
#         {"text":"Greenland is the largest island in the world.","answer":"True",},
#         {"text":"There are more countries in South America than Africa.","answer":"False",},
#         {"text":"Alaska has the most active volcanoes of any state in the United States.","answer":"True",},
#         {"text":"China has the longest coastline in the world.","answer":"False",},
#         {"text":"Vatican City is the smallest country in the world.","answer":"True",},
#         {"text":"Venezuela is home to the world's highest waterfall.","answer":"True",},
#         {"text":"Russia has a larger surface area than Pluto.","answer":"True",},
#         {"text":"There are as many stars in space than there are grains of sand on every beach in the world.","answer":"False",},
#         {"text":"For every human on Earth there are 1.6 million ants.","answer":"True",},
#         {"text":"On Jupiter and Saturn it rains diamonds. ","answer":"True",},
#         {"text":"Python is developed by Guido van Rossum","answer":"",},
#         {"text":"Python runs on the chrome browser","answer":"False",},
#         {"text":"Python is a machine language","answer":"True",},
#         {"text":"Python is a interpreted language","answer":"True",},
#         {"text":"Python is a case sensitive language","answer":"True",},
#         {"text":"Shakespeare made up the name “Sarah” for his play Merchant of Venice.","answer":"False",},
#         {"text":"Rhode Island is the closest US state to Africa.","answer":"True",},
#         {"text":"There are 10 times more bacteria in your body than actual body cells.","answer":"True",},
#         {"text":"An octopus has three hearts.","answer":"True",},
#         {"text":"A banana is a berry.","answer":"False",},
#         ]
# question_data = [
#         {"type":"boolean",
#          "difficulty":"easy",
#          "category":"Science: Computers",
#          "question":"Linux was first created as an alternative to Windows XP.",
#          "correct_answer":"False",
#          "incorrect_answers":["True"]
#          },
#         {"type":"boolean",
#          "difficulty":"easy",
#          "category":"History",
#          "question":"Thomas Crapper was a plumber who invented the flushing toilet.",
#          "correct_answer":"False",
#          "incorrect_answers":["True"]},
#         {"type":"boolean",
#          "difficulty":"easy",
#          "category":"Entertainment: Film",
#          "question":"George Lucas directed the entire original Star Wars trilogy.",
#          "correct_answer":"False",
#          "incorrect_answers":["True"]},
#         {"type":"boolean",
#          "difficulty":"medium",
#          "category":"Science &amp; Nature",
#          "question":"Steel is an alloy of Iron and Carbon.",
#          "correct_answer":"True",
#          "incorrect_answers":["False"]},
#         {"type":"boolean",
#          "difficulty":"easy",
#          "category":"Entertainment: Video Games",
#          "question":"&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.",
#          "correct_answer":"True",
#          "incorrect_answers":["False"]},
#         {"type":"boolean",
#          "difficulty":"medium",
#          "category":"General Knowledge",
#          "question":"Furby was released in 1998.",
#          "correct_answer":"True",
#          "incorrect_answers":["False"]},
#         {"type":"boolean",
#          "difficulty":"medium",
#          "category":"Entertainment: Video Games",
#          "question":"In Riot Games &quot;League of Legends&quot; the name of Halloween event is called &quot;The Reckoning&quot;.",
#          "correct_answer":"False",
#          "incorrect_answers":["True"]},
#         {"type":"boolean","difficulty":"medium","category":"Art","question":"Venus of Willendorf is one of the earliest works of art, depicting the planets Mars and Venus embrace in the heavens at night.",
#          "correct_answer":"False",
#          "incorrect_answers":["True"]},
#         {"type":"boolean",
#          "difficulty":"medium",
#          "category":"Entertainment: Music",
#          "question":"Green Day&#039;s album &#039;American Idiot&#039; is considered a &quot;punk rock opera.&quot;",
#          "correct_answer":"True",
#                                                                                                                                                                                                                                                                      "incorrect_answers":["False"]},
#         {"type":"boolean",
#          "difficulty":"easy",
#          "category":"Entertainment: Video Games",
#          "question":"The Mann Co. Store from Team Fortress 2 has the slogan &quot;We hire mercenaries and get in fights&quot;.",
#          "correct_answer":"False",
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "incorrect_answers":["True"]}
# ]